export const enum Commands {
    BASE_STATUS = 8,
    START_COMPARE = 16,
    UPLOAD_COMPARE = 17,
    GET_COMPARISON_RESULTS = 18,
    UPLOAD_SRCH = 32,
    SRCH_STATUS = 64,
    CAPTURED_FACES = 80,
    RECOGNITION_STATS = 128,
    MATCHED_FACES = 129,
}

export const enum AdminCommands {
    BASE_STATUS = 8,
    SECTOR_REQUEST_INIT = 192,
    SECTOR_REQUEST_STATUS = 193,
    SECTOR_REQUEST_RESULT = 194,
    SECTOR_STATS_INIT = 200,
    SECTOR_STATS_RESULT = 201,
    INSERT_INIT = 204,
    INSERT_STATUS = 205,
    INSERT_GET_FACES = 206,
    INSERT_PROCESS = 207,
    DELETE_INIT = 208,
    DELETE_STATUS = 209,
}

export const enum VideoCommands {
    VIDEO_UPLOAD = 240,
    VIDEO_STATUS = 242,
    VIDEO_RESULT = 244,
}
