name: Package Audit

on:
  push:
    paths:
      - package.json
      - package-lock.json
  pull_request:
    paths:
      - package.json
      - package-lock.json
  workflow_dispatch:

jobs:
  audit-npm:
    name: NPM Audit
    runs-on: ubuntu-latest

    steps:
      - name: Audit with NPM
        uses: myrotvorets/composite-actions/node-package-audit@master

  audit-retire:
    name: RetireJS Check
    runs-on: ubuntu-latest

    steps:
      - name: Audit with Retire.js
        uses: myrotvorets/composite-actions/node-package-audit-retirejs@master
        with:
          registry-url: https://npm.pkg.github.com
